"""Initial schema

Revision ID: 21588084b8e4
Revises: 
Create Date: 2026-02-25 04:18:54.846787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21588084b8e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('hashed_refresh_token', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('target_companies', sa.JSON(), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('cgpa', sa.String(length=10), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('portfolio_url', sa.String(length=300), nullable=True),
    sa.Column('twitter_url', sa.String(length=300), nullable=True),
    sa.Column('leetcode_username', sa.String(length=100), nullable=True),
    sa.Column('codeforces_username', sa.String(length=100), nullable=True),
    sa.Column('codechef_username', sa.String(length=100), nullable=True),
    sa.Column('gfg_username', sa.String(length=100), nullable=True),
    sa.Column('hackerrank_username', sa.String(length=100), nullable=True),
    sa.Column('atcoder_username', sa.String(length=100), nullable=True),
    sa.Column('is_college_public', sa.Boolean(), nullable=True),
    sa.Column('is_cgpa_public', sa.Boolean(), nullable=True),
    sa.Column('is_scores_public', sa.Boolean(), nullable=True),
    sa.Column('is_streak_public', sa.Boolean(), nullable=True),
    sa.Column('is_email_public', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('evaluation_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('eval_type', sa.String(length=20), nullable=True),
    sa.Column('score_relevance', sa.Float(), nullable=True),
    sa.Column('score_star_structure', sa.Float(), nullable=True),
    sa.Column('score_clarity', sa.Float(), nullable=True),
    sa.Column('score_tone_confidence', sa.Float(), nullable=True),
    sa.Column('score_depth', sa.Float(), nullable=True),
    sa.Column('score_specificity', sa.Float(), nullable=True),
    sa.Column('score_vocabulary', sa.Float(), nullable=True),
    sa.Column('score_impact_results', sa.Float(), nullable=True),
    sa.Column('score_filler_control', sa.Float(), nullable=True),
    sa.Column('score_pacing', sa.Float(), nullable=True),
    sa.Column('score_conciseness', sa.Float(), nullable=True),
    sa.Column('score_enthusiasm', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('score_band', sa.String(length=20), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('sample_answer', sa.Text(), nullable=True),
    sa.Column('power_words', sa.JSON(), nullable=True),
    sa.Column('filler_words_detected', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_sessions_created_at'), 'evaluation_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluation_sessions_user_id'), 'evaluation_sessions', ['user_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('per_category_scores', sa.JSON(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_created_at'), 'interview_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('interview_tracker',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('date_applied', sa.Date(), nullable=False),
    sa.Column('current_status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_tracker_created_at'), 'interview_tracker', ['created_at'], unique=False)
    op.create_index(op.f('ix_interview_tracker_current_status'), 'interview_tracker', ['current_status'], unique=False)
    op.create_index(op.f('ix_interview_tracker_user_id'), 'interview_tracker', ['user_id'], unique=False)
    op.create_table('posts',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('round_type', sa.String(length=50), nullable=True),
    sa.Column('flair', sa.String(length=20), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_table('practice_streaks',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_streaks_created_at'), 'practice_streaks', ['created_at'], unique=False)
    op.create_index(op.f('ix_practice_streaks_user_id'), 'practice_streaks', ['user_id'], unique=False)
    op.create_table('readiness_scores',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('streak_weight', sa.Float(), nullable=True),
    sa.Column('evaluation_weight', sa.Float(), nullable=True),
    sa.Column('dsa_weight', sa.Float(), nullable=True),
    sa.Column('ats_weight', sa.Float(), nullable=True),
    sa.Column('mock_weight', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_readiness_scores_created_at'), 'readiness_scores', ['created_at'], unique=False)
    op.create_table('resume_scans',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('keyword_gaps', sa.JSON(), nullable=True),
    sa.Column('overall_suggestions', sa.JSON(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_scans_created_at'), 'resume_scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_resume_scans_user_id'), 'resume_scans', ['user_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('weak_areas', sa.JSON(), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_created_at'), 'study_plans', ['created_at'], unique=False)
    op.create_table('comments',
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('votes',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('vote_type', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votes_created_at'), 'votes', ['created_at'], unique=False)
    op.create_index(op.f('ix_votes_post_id'), 'votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_post_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_created_at'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_study_plans_created_at'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_resume_scans_user_id'), table_name='resume_scans')
    op.drop_index(op.f('ix_resume_scans_created_at'), table_name='resume_scans')
    op.drop_table('resume_scans')
    op.drop_index(op.f('ix_readiness_scores_created_at'), table_name='readiness_scores')
    op.drop_table('readiness_scores')
    op.drop_index(op.f('ix_practice_streaks_user_id'), table_name='practice_streaks')
    op.drop_index(op.f('ix_practice_streaks_created_at'), table_name='practice_streaks')
    op.drop_table('practice_streaks')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_interview_tracker_user_id'), table_name='interview_tracker')
    op.drop_index(op.f('ix_interview_tracker_current_status'), table_name='interview_tracker')
    op.drop_index(op.f('ix_interview_tracker_created_at'), table_name='interview_tracker')
    op.drop_table('interview_tracker')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_created_at'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_evaluation_sessions_user_id'), table_name='evaluation_sessions')
    op.drop_index(op.f('ix_evaluation_sessions_created_at'), table_name='evaluation_sessions')
    op.drop_table('evaluation_sessions')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
